### ISSUE TITLE
Gui says that my xmr address is invalid but it's not

### ISSUE THREAD

**Issue by grayson676** [UnstoppableSwap/unstoppableswap-gui#104]
## Expected Behavior

The app should recognize 47twEvoCwQbNwgbiFKEbz44B52sEf3a2Xc6kLcprXsfpWYts24w4BfoWtgChV8jjTW93WPhgbmComLTegvzguiTW6TivNuZ
as a valid xmr address 

## Current Behavior
The app does not recognize 47twEvoCwQbNwgbiFKEbz44B52sEf3a2Xc6kLcprXsfpWYts24w4BfoWtgChV8jjTW93WPhgbmComLTegvzguiTW6TivNuZ
as being a valid address 

## Steps to Reproduce

1. Open UnstoppableSwap Gui
2. Put 47twEvoCwQbNwgbiFKEbz44B52sEf3a2Xc6kLcprXsfpWYts24w4BfoWtgChV8jjTW93WPhgbmComLTegvzguiTW6TivNuZ as xmr redeem address 
3. It says it's invalid  

## Possible Solution (Not obligatory)

IDFK

## Your Environment

- Operating System and version : Manjaro Linux 5.17.1-3-MANJARO

**Comment by binarybaron** [comment]
The GUI so on testnet unless you have switched the environment variable TESTNET to false. The address you provided is not a stagenet address and therefore invalid.

**Comment by mognify** [comment]
> The GUI so on testnet unless you have switched the environment variable TESTNET to false. The address you provided is not a stagenet address and therefore invalid.

where do we do this on the GUI?

**Comment by binarybaron** [comment]
Please update to the latest version and try again!
