### ISSUE TITLE
Fails to Build on Pop!_OS 22.04 Linux

### ISSUE THREAD

**Issue by ChiefGyk3D** [UnstoppableSwap/unstoppableswap-gui#106]
## Expected Behavior
npm install should work

## Current Behavior
fails to build

Logs:
https://pastebin.com/wpeNp2H1

- Node version : 16.15.0
- Operating System and version : Pop!_OS 22.04

**Comment by binarybaron** [comment]
Can you try installing python (python2)?

```
1930 error /bin/sh: 1: python: not found
```
