### ISSUE TITLE
No swap providers listed?

### ISSUE THREAD

**Issue by outhud** [UnstoppableSwap/unstoppableswap-gui#107]
## Summary

On version 0.3.0, I see no swap providers listed, and have not been able to add any either.

I tried adding some from the list on https://unstoppableswap.net/ including the peer IDs from there, but it seems they don't get added to the (empty) list in the GUI.

**Comment by binarybaron** [comment]
Try launching the GUI with the environment variable `TESTNET=true`. This will switch the GUI to mainnet and you'll see the providers. The reason none are displayed is because there aren't always online testnet providers.
