### ISSUE TITLE
How to know the address is from testnet?

### ISSUE THREAD

**Issue by hui09-m** [UnstoppableSwap/unstoppableswap-gui#111]
## Summary

I have generated many recieve addresses, I use it to change, but it says not valid. How to know the address is from testnet? Is the beginning of address any different？

**Comment by binarybaron** [comment]
What wallet are you using? You need bech32 native addresses

**Comment by hui09-m** [comment]
> What wallet are you using? You need bech32 native addresses
Well， Monero wallet. The address I generated are all start with"8", not valid testnet addresses.

**Comment by binarybaron** [comment]
You need to create a Monero stagenet wallet.

See here: https://monerodocs.org/infrastructure/networks/
