### ISSUE TITLE
Swap popup staying indefinitely in progress

### ISSUE THREAD

**Issue by promesante** [UnstoppableSwap/unstoppableswap-gui#112]
## Expected Behavior

![image](https://user-images.githubusercontent.com/18708591/188752765-3a297171-514e-4e99-97d8-4fb45b42df25.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/18708591/188753329-2df1a710-3fb8-4773-8212-9b3253b972b0.png)

## Steps to Reproduce

I installed unstoppableswap-gui as explained in section "Installation" of project's README, and started the gui combining instructions of both of the following documents:
1. "Swap on Testnet/Stagenet": I've got electrum and monero-wallet-cli started
2. "Installation" instructions given in the README:

```
npm install
TESTNET=true npm start
```

As I installed the gui, it began working right, as shown in the "Swap on Testnet/Stagenet" doc but, for the last couple days, issue depicted above began arosing.

## Your Environment

- Node version : 18.7.0
- Operating System and version : MacOS Monterey 12.0.1

I haven't been able to install unstoppable-gui as explained in section [Swap on Testnet/Stagenet](https://github.com/UnstoppableSwap/unstoppableswap-gui/blob/main/docs/SWAP_TESTNET.md) of its documentation due to security restrictions on my Mac.

Furthermore, logs printed in the CLI report the following error five times:

```
[1662149717387] ERROR (20618 on MBRU309588): Failed to read database
    error: "Error: SQLITE_CANTOPEN: unable to open database file"
```

Full log attached.
[startup.log](https://github.com/UnstoppableSwap/unstoppableswap-gui/files/9501366/startup.log)

And in the directory watched for sqlite database according to that log:

```
[1662082215155] INFO (45295 on MBRU309588): Watching database files
    primaryFile: "/Users/a309588/Library/Application Support/xmr-btc-swap/cli/testnet/sqlite"
    walFile: "/Users/a309588/Library/Application Support/xmr-btc-swap/cli/testnet/sqlite-wal"
    shmFile: "/Users/a309588/Library/Application Support/xmr-btc-swap/cli/testnet/sqlite-shm"
```

In that directory, those sqlite databases are actually there: according to what I observed, they are created there by the [xmr-btc-swap](https://github.com/comit-network/xmr-btc-swap) tool, run the following way:

```
$> cargo run --bin asb -- --testnet start
```

Any idea on what's going on, what I might be doing wrong, and what I should do in order to get this swap popup displayed ok again?

Thanks in advance

**Comment by binarybaron** [comment]
This behaviour has been made more clear in recent version. If we fail to connect to the public registry, we'll tell the user accordingly. If there are not active provider, we'll make that clear as well (this is most likely the issue here)
