### ISSUE TITLE
Cant install on mac M1

### ISSUE THREAD

**Issue by Janaka-Steph** [UnstoppableSwap/unstoppableswap-gui#115]
System: MacOS 12.6 M1
I downloaded the latest release for Mac (arm64.dmg). When trying to run I get this error 
<img width="263" alt="Screenshot 2022-10-14 at 10 13 08" src="https://user-images.githubusercontent.com/4022128/195797087-9905ff6b-5e13-41a0-aaf3-675e8a3773ab.png">

**Comment by lsc64** [comment]
Not sure why the usual workarounds (e.g. right-click > open) don't work, but you can clear the quarantine flag through your terminal and then open it.

`xattr -d com.apple.quarantine /path/to/UnstoppableSwap.app`
or clear everything
`xattr -cr /path/to/UnstoppableSwap.app`
