### ISSUE TITLE
time lag [DEX]

### ISSUE THREAD

**Issue by tjallemaal** [UnstoppableSwap/unstoppableswap-gui#120]
## Summary

Hi! Thanks for building this great tool.

Not having used _atomic swaps_ before, I would like to ask about the swap _time frame_.

The coins I would like to trade away are still on a CEX, so it may take a while until the CEX sends the coins to the swap address. Is this time lag an issue? If this _is_ an issue I will transfer the assets to my wallet first, then do the swap!

THX again

**Comment by binarybaron** [comment]
You have to minutes to send the funds to the address provided. However after those 2 minutes expire the funds stay in the internal wallet. If you then start a new swap the funds you previously provided will be used for that.
