### ISSUE TITLE
Make .deb packages available, please!

### ISSUE THREAD

**Issue by BeachBush** [UnstoppableSwap/unstoppableswap-gui#124]
Unfortunately .AppImage packages normally needs the "kernel.unprivileged_userns_clone" kernel flag set to "1".

Almost all Linux users with hardened kernels have the "kernel.unprivileged_userns_clone" parameter changed to "0".

Making impossible to run the .AppImages packages... Error messages:
```
$ ./UnstoppableSwap-0.3.0.AppImage 
[20728:1120/164615.421073:FATAL:setuid_sandbox_host.cc(158)] 
The SUID sandbox helper binary was found, but is not configured correctly. 
Rather than run without sandboxing I'm aborting now. 
You need to make sure that /tmp/.mount_UnstopElnQ18/chrome-sandbox 
is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

YES... I know it's possible to temporary change the flag with "a simple command":

`$ sudo sysctl -w kernel.unprivileged_userns_clone=1`

BUT it's hard to anyone really concerned about operating systems security to "disable" a safety measure... especially when it comes to cryptocurrency related applications.

[TL;DR fixed with: **kernel.unprivileged_userns_clone=0**]
For your reference (from 2022-01-21): [Nasty Linux kernel bug found and fixed](https://www.zdnet.com/article/nasty-linux-kernel-bug-found-and-fixed/)

**Comment by binarybaron** [comment]
.deb images are part of every new release from now on

https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.5.1

**Comment by slrslr** [comment]
@binarybaron You are missing a .deb file in latest [v1.0.0-rc.1](https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v1.0.0-rc.1) I am wondering if next rc may have it or if I should transform my updating script to something else like AppImage.

**Comment by binarybaron** [comment]
> @binarybaron You are missing a .deb file in latest [v1.0.0-rc.1](https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v1.0.0-rc.1) I am wondering if next rc may have it or if I should transform my updating script to something else like AppImage.

We cannot yet build .deb image because it will break the inbuilt auto updater. It's on our roadmap but might take a while. For now, I recommend you use the AppImage.
