### ISSUE TITLE
Tor Error in Linux AppImage

### ISSUE THREAD

**Issue by ACK-J** [UnstoppableSwap/unstoppableswap-gui#130]
## Expected Behavior

The application should connect to a Tor circut. 

## Current Behavior

Each time I click the Start Tor button within the GUI, this error appears within the debugging log and Tor never starts. 
I am using v0.4.4 appimage on Popos.

```
UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, chmod '/tmp/.mount_Unstopy44hb9/resources/bin/tor'
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by binarybaron** [comment]
Please try version https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.4.5

**Comment by ACK-J** [comment]
@binarybaron Can confirm v0.4.5 fixed the issue. Thanks again for the quick patch!
