### ISSUE TITLE
Ran out of Space During Swap

### ISSUE THREAD

**Issue by galaxy-brain-not** [UnstoppableSwap/unstoppableswap-gui#138]
Very niche, so I understand if I'm just out of luck, but my computer ran out of space after both locks were confirmed, causing the swap to crash.  Attempting to resume it also fails, with the error message "Error: failed to initialize Bitcoin wallet" caused by "read curropted data at file offset None backtrace ()"

Is there any way to resume and/or recover funds?  Happy to post logs if needed, but didn't right away in case they contain sensitive info. 

Thanks so much, this was really dumb on my part :)

**Comment by galaxy-brain-not** [comment]
Thanks so much, that worked!! (as in, since it had been >12 hr, I was able to successfully initiate the bitcoin refund transaction)  I'll donate some my recovered funds to this project :)

**Comment by binarybaron** [comment]
Awesome, 👍
