### ISSUE TITLE
I get the following error when I run the project

### ISSUE THREAD

**Issue by CodeSkyCode** [UnstoppableSwap/unstoppableswap-gui#141]
When I npm install I get the following error. version of node.js  is v14.19.0. verson of npm is 6.14.16. Can you give me some hints.
<img width="1372" alt="截屏2023-04-06 23 00 28" src="https://user-images.githubusercontent.com/124372032/230424787-b650e4a8-ba27-4fd4-a95b-14b27e0b541d.png">
<img width="1268" alt="截屏2023-04-06 23 23 16" src="https://user-images.githubusercontent.com/124372032/230425440-588fff44-3dec-4dd2-beee-3e2736642647.png">

**Comment by m4nos** [comment]
try running it with node version 16. it is mentioned in the readme

**Comment by binarybaron** [comment]
Running with node 16 and just running `npm install` should work.

Feel free to reopen.
