### ISSUE TITLE
PGP-sign releases

### ISSUE THREAD

**Issue by chaserene** [UnstoppableSwap/unstoppableswap-gui#145]
please establish a release signing PGP key pair where your release manager(s) have sole custody of the private key, and sign all binary releases, preferably with a separate <filename>.<extension>.sign file for each binary. this will allow your users to verify that, as long as the key is uncompromised, binaries came from the same source.

**Comment by binarybaron** [comment]
I have GPG signed the latest 0.6.2 release: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.2. See the release notes on where to find my signing key and how to verify the validity of the release files.

**Comment by binarybaron** [comment]
> seriously, thank you. for 99% of the developers this is an insurmountable task.

Sure thing. I realize this is important.
