### ISSUE TITLE
Unstoppableswap never detected my btc. Blockchair says otherwise.

### ISSUE THREAD

**Issue by pscopic** [UnstoppableSwap/unstoppableswap-gui#150]
## Expected Behavior

The GUI should have recognized the BTC I sent to the address it provided: bc1q9qq285pwq6rzl55dkdypy2k4mn3rx8wd8mx9z3
(see attached)
Blockchair shows I sent to this address with txid: dab63677af1c518e6bc8c7b0b49fecedad06c60f21852c106bbc734453d6cf73
![blockchair-screenshot-2023-08-09 2 11 00 AM](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/24592982/bd0a4422-3b15-4d03-bed3-4c06a74d4cd2)

The amount of BTC sent was 0.011141

## Current Behavior

The screen never changed to acknowledge receiving my BTC.
![unstoppable-screen-of-btc-address-to-send-to-2023-08-09 2 09 43 AM](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/24592982/89183510-ff1a-4fa3-9bd2-f28c0d0d402f)

I never received XMR return.

When switching debug switch I have two logs available, swap-standard-output and swap-state. See attached for swap-standard-output. 
[swap-standard-output.log](https://github.com/UnstoppableSwap/unstoppableswap-gui/files/12300930/swap-standard-output.log)

This log shows connection was lost for awhile before reconnecting. But upon reconnecting I would expect it to show that my btc transaction went through as reflected by blockchair. But it does not.

The atomic swap exchange I used was beta.unstoppableswap.net which was the recommended exchange.

Please advise.

- Operating System and version : ChromeOS Version 115.0.5790.160 (Official Build) (64-bit)
- UnstoppableSwap version 5

**Comment by binarybaron** [comment]
Thanks for reporting this issue. First and foremost: Your funds are safe. They are inside the internal Bitcoin wallet. This issue is most likely caused by a problem with the connection with the Electrum server which causes the CLI (the program performing the swap) to fail to retrieve the correct balance.

Please try to go to the Wallet tab and see if the correct balance is displayed. You can either withdraw the funds to your own wallet or try to initiate a new swap.

**Comment by pscopic** [comment]
> Thanks for reporting this issue. First and foremost: Your funds are safe. They are inside the internal Bitcoin wallet. This issue is most likely caused by a problem with the connection with the Electrum server which causes the CLI (the program performing the swap) to fail to retrieve the correct balance.
> 
> Please try to go to the Wallet tab and see if the correct balance is displayed. You can either withdraw the funds to your own wallet or try to initiate a new swap.

Thank you, that worked perfectly. I was hesitant to exit out and cancel the swap but apparently that's all that needed to be done. Perhaps a warning message that it's perfectly ok to cancel out of the transaction if it doesn't appear to receive the coin at the address it provides.  Appreciate your immediate response.
