### ISSUE TITLE
Help. Wanted to try atomic swap and first purchased bitcoin from Bisq. Transaction Fee too low. Transaction stuck in mempool for 3 days.

### ISSUE THREAD

**Issue by Shr3k455** [UnstoppableSwap/unstoppableswap-gui#153]
As the title says. I first purchased bitcoin from bisq and withdrew it all and sent it directly to UnstoppableSwap. Accidentally made the transaction fee too low through Bisq and have been stuck at 0 of 6 confirmations for 3 days. 

What are my options? RBF does not appear possible through bisq, and since I sent it directly to a swap provider, I have no clue how to initiate CPFP.

Some places say the transaction will be thrown out of the mempool in 72 hours, other say weeks, one said indefinitely. Please please help, thank you.

**Comment by binarybaron** [comment]
Which state is your transaction in? Has the Bitcoin been "locked"?

Try to keep an eye on the transaction. If it gets confirmed resume the swap and finish. If the transaction gets dropped (not confirmed). You can probably just withdraw it from Bisq with a higher fee.

**Comment by binarybaron** [comment]
Closing this
