### ISSUE TITLE
Swap not working due (maybe RPC connection problem)

### ISSUE THREAD

**Issue by zRavexx** [UnstoppableSwap/unstoppableswap-gui#154]
4th step (Redeeming your Monero) is not going through.
I checked the Debug menu and i i've got this message:
"Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists."

I also checked the "monero-wallet-rpc.txt" file. There i got ERROR/WARNING messages which are saying:
"2023-08-17 11:58:23.164	6080	WARNING	wallet.rpc	src/wallet/wallet_rpc_server.cpp:4620	Starting wallet RPC server
2023-08-17 11:58:26.984	[RPC0]	WARNING	wallet.wallet2	src/wallet/wallet2.cpp:5569	Loaded wallet keys file, with public address: DELETED FOR SAFETY PURPOSES
2023-08-17 11:58:29.051	[RPC0]	ERROR	wallet.rpc	src/wallet/wallet_rpc_server.cpp:3622	boost::filesystem::exists(wallet_file, ignored_ec). THROW EXCEPTION: error::file_exists
2023-08-17 11:58:29.330	[RPC0]	WARNING	wallet.wallet2	src/wallet/wallet2.cpp:5569	Loaded wallet keys file, with public address: DELETED FOR SAFETY PURPOSES
2023-08-17 12:02:34.190	1700	INFO	logging	contrib/epee/src/mlog.cpp:273	New log categories: *:WARNING,net:FATAL,net.http:FATAL,net.ssl:FATAL,net.p2p:FATAL,net.cn:FATAL,daemon.rpc:FATAL,global:INFO,verify:FATAL,serialization:FATAL,daemon.rpc.payment:ERROR,stacktrace:INFO,logging:INFO,msgwriter:INFO

So i guess something with the RPC Connection is not working. Could someone please help me ?
Thank you very much.

## Your Environment
- UnstoppableSwap Version: 0.5.0
- Operating System and version: Windows 10 running on a virtual machine.

Constantly Loading:
![image](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/142545567/0c3ce328-f43c-4a17-9817-d4233f130a25)

**Comment by binarybaron** [comment]
Hey thanks for reporting this issue,
first of all your funds are safe. They are stored in a Monero wallet only you have the keys to.


The swap-cli is having trouble redeeming the Monero. This issue has occured before and we are still investigating.

Now, to recover your XMR funds you have to do the following:
1. Download the swap-cli from https://github.com/comit-network/xmr-btc-swap/releases/tag/0.12.2 for your system. This is the program that's used in the background to facilitate the swaps.
2. Get the ID of your swap from the "History" tab
3. Open PowerShell, navigate to the directory of the swap.exe file using cd (e.g cd Desktop)
4. Run this command:
./swap monero-recovery --swap-id YOUR_SWAP_ID
5. You'll get a view key and a spend key printed to the console.
6. Use the monero-wallet-gui to restore the wallet from the printed keys. Use a restore height a few days before your swap was done (https://www.getmonero.org/resources/user-guides/restore_from_keys.html)

I apologize for the trouble. We'll make sure this issue is fixed in a future release.

**Comment by binarybaron** [comment]
Also, could you please share the logs of your swap us. It'll help us debug the issue better and find a solution quicker. Go the History tab, click on the expand icon and click "View Log".

**Comment by zRavexx** [comment]
Thank you for your answer, unfortunately it is still not working.

I did download the swap-cli -> put in on my Desktop -> opened Powershell -> directed to my Desktop (where the swap-cli is) -> run the command: ./swap monero-recovery --swap-id YOUR_SWAP_ID -> Got a Error message (see attached photo)

I tried and checked it many times that i spelled the Swap ID correctly.

![image](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/142545567/d3a2e987-dafa-4faf-96db-ec4e8e1c60ea)

**Comment by zRavexx** [comment]
Thank you for your answer, unfortunately it is still not working.

I did download the swap-cli -> put in on my Desktop -> opened Powershell -> directed to my Desktop (where the swap-cli is) -> run the command: ./swap monero-recovery --swap-id YOUR_SWAP_ID -> Got a Error message (see attached photo)

I tried and checked it many times that i spelled the Swap ID correctly.

![image](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/142545567/78db573f-d709-4183-a3a8-0dddb4689a7d)

**Comment by zRavexx** [comment]
Here are the logs. For safety purposes i deleted some ID's and replaced them with:"Deleted for safety purposes.". I really don't know if someone could get them and steal them and can get my money with it, i don't really know how it works so i just wanted to be safe.


The Log;
{"timestamp":"2023-08-17T10:10:26.546475Z","level":"INFO","fields":{"message":"Logging initialized to C:\\Users\\vboxuser\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\logs"}}
{"timestamp":"2023-08-17T10:10:26.546588Z","level":"DEBUG","fields":{"message":"Using existing sqlite database."}}
{"timestamp":"2023-08-17T10:10:26.547984Z","level":"DEBUG","fields":{"message":"Reading in seed from C:\\Users\\vboxuser\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\seed.pem"}}
{"timestamp":"2023-08-17T10:10:27.051771Z","level":"DEBUG","fields":{"message":"RPC exec path: C:\\Users\\vboxuser\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\monero\\monero-wallet-rpc.exe"}}
{"timestamp":"2023-08-17T10:10:28.073953Z","level":"DEBUG","fields":{"message":"RPC version output: Monero 'Fluorine Fermi' (v0.18.1.2-release)\r\n"}}
{"timestamp":"2023-08-17T10:10:28.074269Z","level":"DEBUG","fields":{"message":"Starting monero-wallet-rpc","port":"54106"}}
{"timestamp":"2023-08-17T10:10:33.714794Z","level":"DEBUG","fields":{"message":"Opened Monero wallet","monero_wallet_name":"swap-tool-blockchain-monitoring-wallet"}}
{"timestamp":"2023-08-17T10:10:35.767044Z","level":"DEBUG","fields":{"message":"Network layer initialized","peer_id":"DELETED FOR SAFETY PURPOSES"}}
{"timestamp":"2023-08-17T10:10:35.767114Z","level":"DEBUG","fields":{"message":"Requesting quote"}}
{"timestamp":"2023-08-17T10:10:35.876921Z","level":"INFO","fields":{"message":"Connected to Alice at /dns4/beta.unstoppableswap.net/tcp/9939/p2p/DELETED FOR SAFETY PURPOSES"}}
{"timestamp":"2023-08-17T10:10:35.917212Z","level":"INFO","fields":{"message":"Received quote","price":"0.00558376 BTC","minimum_amount":"0.0005 BTC","maximum_amount":"0.15 BTC"}}
{"timestamp":"2023-08-17T10:10:35.966466Z","level":"INFO","fields":{"message":"Determined swap amount","amount":"0.00257563 BTC","fees":"0.00001292 BTC"}}
{"timestamp":"2023-08-17T10:10:35.987978Z","level":"DEBUG","fields":{"message":"Advancing state","state":"quote has been requested"}}
{"timestamp":"2023-08-17T10:10:36.025939Z","level":"DEBUG","fields":{"message":"Estimated fee for transaction","weight":"548","fee_rate":"10.58","sats_per_vbyte":"1449.460"}}
{"timestamp":"2023-08-17T10:10:36.066206Z","level":"DEBUG","fields":{"message":"Estimated fee for transaction","weight":"596","fee_rate":"10.58","sats_per_vbyte":"1576.420"}}
{"timestamp":"2023-08-17T10:10:38.795936Z","level":"INFO","fields":{"message":"Starting new swap","swap_id":"DELETED FOR SAFETY PURPOSES"}}
{"timestamp":"2023-08-17T10:10:38.808832Z","level":"DEBUG","fields":{"message":"Advancing state","state":"execution setup done"}}
{"timestamp":"2023-08-17T10:10:38.838670Z","level":"INFO","fields":{"message":"Published Bitcoin transaction","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","kind":"lock"}}
{"timestamp":"2023-08-17T10:10:38.855961Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is locked"}}
{"timestamp":"2023-08-17T10:10:39.136506Z","level":"DEBUG","fields":{"message":"Found relevant Bitcoin transaction","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","status":"unseen"}}
{"timestamp":"2023-08-17T10:10:39.136641Z","level":"INFO","fields":{"message":"Waiting for Alice to lock Monero"}}
{"timestamp":"2023-08-17T10:11:41.990409Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"in mempool","old_status":"unseen"}}
{"timestamp":"2023-08-17T10:31:22.988096Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803594}}
{"timestamp":"2023-08-17T10:34:27.846183Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803595}}
{"timestamp":"2023-08-17T10:34:27.865205Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2023-08-17T10:35:27.997455Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803596}}
{"timestamp":"2023-08-17T10:35:28.017113Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2023-08-17T10:35:52.554793Z","level":"INFO","fields":{"message":"Alice locked Monero","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178"}}
{"timestamp":"2023-08-17T10:35:52.558919Z","level":"DEBUG","fields":{"message":"Advancing state","state":"XMR lock transaction transfer proof received"}}
{"timestamp":"2023-08-17T10:35:52.559464Z","level":"INFO","fields":{"message":"Waiting for Monero transaction finality","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","target_confirmations":"10"}}
{"timestamp":"2023-08-17T10:35:52.655757Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"1","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:37:52.606950Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"2","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:39:16.606328Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"3","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:40:28.600037Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"4","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:41:39.206234Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803597}}
{"timestamp":"2023-08-17T10:41:39.223375Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 3 blocks","old_status":"confirmed with 2 blocks"}}
{"timestamp":"2023-08-17T10:42:16.609421Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"5","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:43:04.597559Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"6","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:43:41.537718Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803599}}
{"timestamp":"2023-08-17T10:43:41.616856Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 5 blocks","old_status":"confirmed with 3 blocks"}}
{"timestamp":"2023-08-17T10:46:40.597156Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"7","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:49:04.597348Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"8","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:50:04.604420Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"9","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:50:40.849840Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"51d227856cb84ecc88941aae28b7b65ad2840326dd508f15a2d2c9eb94346178","seen_confirmations":"10","needed_confirmations":"10"}}
{"timestamp":"2023-08-17T10:50:40.863094Z","level":"DEBUG","fields":{"message":"Advancing state","state":"xmr is locked"}}
{"timestamp":"2023-08-17T10:50:40.863513Z","level":"DEBUG","fields":{"message":"Constructed Bitcoin spending transaction","fee":"1449"}}
{"timestamp":"2023-08-17T10:50:40.919310Z","level":"DEBUG","fields":{"message":"Advancing state","state":"encrypted signature is sent"}}
{"timestamp":"2023-08-17T10:50:40.919523Z","level":"DEBUG","fields":{"message":"Constructed Bitcoin spending transaction","fee":"1449"}}
{"timestamp":"2023-08-17T10:50:40.920759Z","level":"DEBUG","fields":{"message":"Found relevant Bitcoin transaction","txid":"402273fe2abdf76bcb684450fc3af8ceb337e89e16ac2e591b51df8709261291","status":"unseen"}}
{"timestamp":"2023-08-17T10:51:59.607621Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"402273fe2abdf76bcb684450fc3af8ceb337e89e16ac2e591b51df8709261291","new_status":"in mempool","old_status":"unseen"}}
{"timestamp":"2023-08-17T10:52:01.783145Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2023-08-17T10:57:09.007115Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803600}}
{"timestamp":"2023-08-17T10:57:09.079684Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 6 blocks","old_status":"confirmed with 5 blocks"}}
{"timestamp":"2023-08-17T10:57:09.079756Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"402273fe2abdf76bcb684450fc3af8ceb337e89e16ac2e591b51df8709261291","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2023-08-17T11:02:18.253128Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803601}}
{"timestamp":"2023-08-17T11:02:18.306678Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"402273fe2abdf76bcb684450fc3af8ceb337e89e16ac2e591b51df8709261291","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2023-08-17T11:02:18.306748Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 7 blocks","old_status":"confirmed with 6 blocks"}}
{"timestamp":"2023-08-17T11:08:29.987578Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":803602}}
{"timestamp":"2023-08-17T11:08:30.049776Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"402273fe2abdf76bcb684450fc3af8ceb337e89e16ac2e591b51df8709261291","new_status":"confirmed with 3 blocks","old_status":"confirmed with 2 blocks"}}
{"timestamp":"2023-08-17T11:08:30.049853Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"7b5f69e61cc83cfb1ae6ff331ae458aa115d03e8ee374cc6fc9772d31a05c75d","new_status":"confirmed with 8 blocks","old_status":"confirmed with 7 blocks"}}
{"timestamp":"2023-08-17T11:16:06.873309Z","level":"INFO","fields":{"message":"Logging initialized to C:\\Users\\vboxuser\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\logs"}}
{"timestamp":"2023-08-17T11:16:06.874026Z","level":"DEBUG","fields":{"message":"Using existing sqlite database."}}
{"timestamp":"2023-08-17T11:16:06.885535Z","level":"DEBUG","fields":{"message":"Reading in seed from C:\\Users\\vboxuser\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\seed.pem"}}
{"timestamp":"2023-08-17T11:16:07.355985Z","level":"DEBUG","fields":{"message":"RPC exec path: C:\\Users\\vboxuser\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\monero\\monero-wallet-rpc.exe"}}
{"timestamp":"2023-08-17T11:16:08.707592Z","level":"DEBUG","fields":{"message":"RPC version output: Monero 'Fluorine Fermi' (v0.18.1.2-release)\r\n"}}
{"timestamp":"2023-08-17T11:16:08.707865Z","level":"DEBUG","fields":{"message":"Starting monero-wallet-rpc","port":"63740"}}
{"timestamp":"2023-08-17T11:16:14.217606Z","level":"DEBUG","fields":{"message":"Opened Monero wallet","monero_wallet_name":"swap-tool-blockchain-monitoring-wallet"}}
{"timestamp":"2023-08-17T11:16:16.242261Z","level":"DEBUG","fields":{"message":"Network layer initialized","peer_id":"DELETED FOR SAFETY PURPOSES"}}
{"timestamp":"2023-08-17T11:16:16.243257Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2023-08-17T11:16:16.252405Z","level":"WARN","fields":{"message":"Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists.: JSON-RPC request failed with code -1: Wallet already exists."}}
{"timestamp":"2023-08-17T11:16:16.252464Z","level":"INFO","fields":{"message":"Falling back to trying to open the the wallet if it already exists","wallet_file_name":"DELETED FOR SAFETY PURPOSES"}}
{"timestamp":"2023-08-17T11:16:16.387315Z","level":"INFO","fields":{"message":"Connected to Alice at /dns4/beta.unstoppableswap.net/tcp/9939/p2p/DELETED FOR SAFETY PURPOSES"}}

**Comment by binarybaron** [comment]
Try adding this flag to the terminal command

./swap --base-dir C:\Users\vboxuser\AppData\Roaming\xmr-btc-swap\cli\ monero-recovery --swap-id YOURSWAPID

Also try running:
/swap --base-dir C:\Users\vboxuser\AppData\Roaming\xmr-btc-swap\cli\ history

**Comment by zRavexx** [comment]
I am getting this Error message: 
![image](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/142545567/b15b82c1-f79b-4a2e-bd94-2230d5190118)

--base-dir isn't working unfortunately but i don't understand why.

**Comment by binarybaron** [comment]
I made a small mistake. Can you try again? I edited my original message

**Comment by zRavexx** [comment]
Hello binarybaron,

it worked! I got access to the wallet and i've sent the monero to another wallet.
Thank you very much for your help, without you my money would be gone :)
