### ISSUE TITLE
Swap failed at Redeeming XMR. Wallet already exists. No connection to daemon

### ISSUE THREAD

**Issue by KracauerB** [UnstoppableSwap/unstoppableswap-gui#156]
## Expected Behavior

Swap completes without error at Redeem XMR step

## Current Behavior

Error: JSON-RPC request failed with code -38: no connection to daemon

## Steps to Reproduce
image: 
<img width="957" alt="Screenshot 2023-08-31 at 9 08 06 PM" src="https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/143765856/f21f585e-22e2-46b1-9016-7e2f108c37ed">

relevant logs: 

> {"timestamp":"2023-09-01T00:54:45.496258Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2023-09-01T00:54:45.499423Z","level":"WARN","fields":{"message":"Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists.: JSON-RPC request failed with code -1: Wallet already exists."}}
{"timestamp":"2023-09-01T00:54:45.499451Z","level":"INFO","fields":{"message":"Falling back to trying to open the the wallet if it already exists","wallet_file_name":"ab317447-d24f-4455-8fb9-b92139da9ebb"}}
{"timestamp":"2023-09-01T00:54:45.887138Z","level":"INFO","fields":{"message":"Connected to Alice at /dns4/beta.unstoppableswap.net/tcp/9939/p2p/12D3KooWMiriru5viqde3BMFLTqPur8Yrjpp4ULFc76ubQLfuYYX"}}
Error: JSON-RPC request failed with code -38: no connection to daemon

Caused by:
    JSON-RPC request failed with code -38: no connection to daemon

## Your Environment

- Node version : Monero GUI 0.18.2.2-release (Qt 5.12.8)
- Operating System and version : Mac OS Ventura 13.4

**Comment by KracauerB** [comment]
I tried again and it worked. Closing this.

**Comment by danrayson** [comment]
Had same symptom logs, after restarting app it worked.
