### ISSUE TITLE
[Please Help] Swap stuck on redeeming your monero.

### ISSUE THREAD

**Issue by weeb042069** [UnstoppableSwap/unstoppableswap-gui#158]
## Expected Behavior
For the XMR to finish the swap and go to my account

## Current Behavior
Everything was working fine till I got to the redeeming XMR portion and now its stuck. I am also scared to click off the transaction cause I heard you could lose your funds like that. If anyone can help me soon that would be very much appreciated I am kinda scared of losing my funds.
![image](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/144289344/f5055511-4a1e-4c3e-a128-85225335ec85)

## Steps to Reproduce
Standard Output
{"timestamp":"2023-09-06T22:04:04.6964506Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806514}}
{"timestamp":"2023-09-06T22:04:04.8064908Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2023-09-06T22:07:00.8556999Z","level":"INFO","fields":{"message":"Alice locked Monero","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455"}}
{"timestamp":"2023-09-06T22:07:00.8760201Z","level":"DEBUG","fields":{"message":"Advancing state","state":"XMR lock transaction transfer proof received"}}
{"timestamp":"2023-09-06T22:07:00.8767179Z","level":"INFO","fields":{"message":"Waiting for Monero transaction finality","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","target_confirmations":"10"}}
{"timestamp":"2023-09-06T22:07:20.7060689Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"1","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:08:53.4687682Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"2","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:09:51.8873805Z","level":"DEBUG","fields":{"message":"Failed to get transaction from daemon","data":"None"}}
{"timestamp":"2023-09-06T22:09:51.8874687Z","level":"WARN","fields":{"message":"`monero-wallet-rpc` failed to fetch transaction, may need to be restarted","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","message":"Failed to get transaction from daemon"}}
{"timestamp":"2023-09-06T22:11:01.0308835Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"3","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:12:27.8923678Z","level":"DEBUG","fields":{"message":"Failed to get transaction from daemon","data":"None"}}
{"timestamp":"2023-09-06T22:12:27.8923873Z","level":"WARN","fields":{"message":"`monero-wallet-rpc` failed to fetch transaction, may need to be restarted","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","message":"Failed to get transaction from daemon"}}
{"timestamp":"2023-09-06T22:13:49.0379193Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"4","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:14:37.041534Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"5","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:17:01.0617625Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"6","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:17:13.0305791Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"7","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:19:01.0306013Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"8","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:22:01.0555092Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"9","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:24:01.0324966Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"10","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:24:01.0483015Z","level":"DEBUG","fields":{"message":"Advancing state","state":"xmr is locked"}}
{"timestamp":"2023-09-06T22:24:01.0503462Z","level":"DEBUG","fields":{"message":"Constructed Bitcoin spending transaction","fee":"3390"}}
{"timestamp":"2023-09-06T22:24:01.2962475Z","level":"DEBUG","fields":{"message":"Advancing state","state":"encrypted signature is sent"}}
{"timestamp":"2023-09-06T22:24:01.2967357Z","level":"DEBUG","fields":{"message":"Constructed Bitcoin spending transaction","fee":"3390"}}
{"timestamp":"2023-09-06T22:24:01.2977967Z","level":"DEBUG","fields":{"message":"Found relevant Bitcoin transaction","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","status":"unseen"}}
{"timestamp":"2023-09-06T22:24:52.0650382Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"in mempool","old_status":"unseen"}}
{"timestamp":"2023-09-06T22:24:54.3115818Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2023-09-06T22:27:59.29487Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806515}}
{"timestamp":"2023-09-06T22:28:00.1195094Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2023-09-06T22:28:00.1195434Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2023-09-06T23:04:41.9446236Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806516}}
{"timestamp":"2023-09-06T23:04:43.8029724Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2023-09-06T23:04:43.8030212Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 3 blocks","old_status":"confirmed with 2 blocks"}}

- Operating System and version : Windows 11 22000.1335

**Comment by weeb042069** [comment]
It is giving me the option to force stop but it says it might have unintended consequences. Should I not turn off my computer with unstoppable swap running?

**Comment by weeb042069** [comment]
this is my new debug log

{"timestamp":"2023-09-06T22:04:04.6964506Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806514}}
{"timestamp":"2023-09-06T22:04:04.8064908Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2023-09-06T22:07:00.8556999Z","level":"INFO","fields":{"message":"Alice locked Monero","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455"}}
{"timestamp":"2023-09-06T22:07:00.8760201Z","level":"DEBUG","fields":{"message":"Advancing state","state":"XMR lock transaction transfer proof received"}}
{"timestamp":"2023-09-06T22:07:00.8767179Z","level":"INFO","fields":{"message":"Waiting for Monero transaction finality","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","target_confirmations":"10"}}
{"timestamp":"2023-09-06T22:07:20.7060689Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"1","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:08:53.4687682Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"2","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:09:51.8873805Z","level":"DEBUG","fields":{"message":"Failed to get transaction from daemon","data":"None"}}
{"timestamp":"2023-09-06T22:09:51.8874687Z","level":"WARN","fields":{"message":"`monero-wallet-rpc` failed to fetch transaction, may need to be restarted","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","message":"Failed to get transaction from daemon"}}
{"timestamp":"2023-09-06T22:11:01.0308835Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"3","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:12:27.8923678Z","level":"DEBUG","fields":{"message":"Failed to get transaction from daemon","data":"None"}}
{"timestamp":"2023-09-06T22:12:27.8923873Z","level":"WARN","fields":{"message":"`monero-wallet-rpc` failed to fetch transaction, may need to be restarted","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","message":"Failed to get transaction from daemon"}}
{"timestamp":"2023-09-06T22:13:49.0379193Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"4","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:14:37.041534Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"5","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:17:01.0617625Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"6","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:17:13.0305791Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"7","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:19:01.0306013Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"8","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:22:01.0555092Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"9","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:24:01.0324966Z","level":"INFO","fields":{"message":"Received new confirmation for Monero lock tx","txid":"964208ca490f73aae3446dd4c412f4ef6883d868eeb99b39f430639406078455","seen_confirmations":"10","needed_confirmations":"10"}}
{"timestamp":"2023-09-06T22:24:01.0483015Z","level":"DEBUG","fields":{"message":"Advancing state","state":"xmr is locked"}}
{"timestamp":"2023-09-06T22:24:01.0503462Z","level":"DEBUG","fields":{"message":"Constructed Bitcoin spending transaction","fee":"3390"}}
{"timestamp":"2023-09-06T22:24:01.2962475Z","level":"DEBUG","fields":{"message":"Advancing state","state":"encrypted signature is sent"}}
{"timestamp":"2023-09-06T22:24:01.2967357Z","level":"DEBUG","fields":{"message":"Constructed Bitcoin spending transaction","fee":"3390"}}
{"timestamp":"2023-09-06T22:24:01.2977967Z","level":"DEBUG","fields":{"message":"Found relevant Bitcoin transaction","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","status":"unseen"}}
{"timestamp":"2023-09-06T22:24:52.0650382Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"in mempool","old_status":"unseen"}}
{"timestamp":"2023-09-06T22:24:54.3115818Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2023-09-06T22:27:59.29487Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806515}}
{"timestamp":"2023-09-06T22:28:00.1195094Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2023-09-06T22:28:00.1195434Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2023-09-06T23:04:41.9446236Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806516}}
{"timestamp":"2023-09-06T23:04:43.8029724Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2023-09-06T23:04:43.8030212Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 3 blocks","old_status":"confirmed with 2 blocks"}}
{"timestamp":"2023-09-06T23:13:06.0818363Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806517}}
{"timestamp":"2023-09-06T23:13:06.9556777Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"confirmed with 3 blocks","old_status":"confirmed with 2 blocks"}}
{"timestamp":"2023-09-06T23:13:06.9557119Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 4 blocks","old_status":"confirmed with 3 blocks"}}
{"timestamp":"2023-09-06T23:28:44.9533968Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":806518}}
{"timestamp":"2023-09-06T23:28:45.8570038Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"confirmed with 5 blocks","old_status":"confirmed with 4 blocks"}}
{"timestamp":"2023-09-06T23:28:45.8570494Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cfc50802d413e6fcdd96aa4e1fd63aed32789d61e38f453bde12ad735af40c85","new_status":"confirmed with 4 blocks","old_status":"confirmed with 3 blocks"}}
{"timestamp":"2023-09-06T21:57:35.266125Z","level":"INFO","fields":{"message":"Logging initialized to C:\\Users\\desgr\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\logs"}}
{"timestamp":"2023-09-06T21:57:35.266266Z","level":"DEBUG","fields":{"message":"Using existing sqlite database."}}
{"timestamp":"2023-09-06T21:57:35.267820Z","level":"DEBUG","fields":{"message":"Reading in seed from C:\\Users\\desgr\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\seed.pem"}}
{"timestamp":"2023-09-06T21:57:37.098856Z","level":"DEBUG","fields":{"message":"RPC exec path: C:\\Users\\desgr\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\monero\\monero-wallet-rpc.exe"}}
{"timestamp":"2023-09-06T21:57:38.132906Z","level":"DEBUG","fields":{"message":"RPC version output: Monero 'Fluorine Fermi' (v0.18.1.2-release)\r\n"}}
{"timestamp":"2023-09-06T21:57:38.133307Z","level":"DEBUG","fields":{"message":"Starting monero-wallet-rpc","port":"55618"}}
{"timestamp":"2023-09-06T21:57:44.838551Z","level":"DEBUG","fields":{"message":"Opened Monero wallet","monero_wallet_name":"swap-tool-blockchain-monitoring-wallet"}}
{"timestamp":"2023-09-06T21:57:46.862737Z","level":"DEBUG","fields":{"message":"Network layer initialized","peer_id":"12D3KooWF1REzmMKvoXv1DpKcAyzA4pMDXx6N4qkDknpqvpCvQYC"}}
{"timestamp":"2023-09-06T21:57:46.862796Z","level":"DEBUG","fields":{"message":"Requesting quote"}}
{"timestamp":"2023-09-06T21:57:47.368828Z","level":"INFO","fields":{"message":"Connected to Alice at /dns4/beta.unstoppableswap.net/tcp/9939/p2p/12D3KooWMiriru5viqde3BMFLTqPur8Yrjpp4ULFc76ubQLfuYYX"}}
{"timestamp":"2023-09-06T21:57:47.598477Z","level":"INFO","fields":{"message":"Received quote","price":"0.00576368 BTC","minimum_amount":"0.0005 BTC","maximum_amount":"0.1656589 BTC"}}
{"timestamp":"2023-09-06T21:57:47.814731Z","level":"INFO","fields":{"message":"Determined swap amount","amount":"0.0057838 BTC","fees":"0.00003021 BTC"}}
{"timestamp":"2023-09-06T21:57:47.821718Z","level":"DEBUG","fields":{"message":"Advancing state","state":"quote has been requested"}}
{"timestamp":"2023-09-06T21:57:48.035414Z","level":"DEBUG","fields":{"message":"Estimated fee for transaction","weight":"548","fee_rate":"24.75","sats_per_vbyte":"3390.750"}}
{"timestamp":"2023-09-06T21:57:48.255923Z","level":"DEBUG","fields":{"message":"Estimated fee for transaction","weight":"596","fee_rate":"24.75","sats_per_vbyte":"3687.750"}}
{"timestamp":"2023-09-06T21:57:51.802960Z","level":"INFO","fields":{"message":"Starting new swap","swap_id":"9f442c10-4925-4a9a-9764-5174e786e694"}}
{"timestamp":"2023-09-06T21:57:51.806108Z","level":"DEBUG","fields":{"message":"Advancing state","state":"execution setup done"}}
{"timestamp":"2023-09-06T21:57:51.919270Z","level":"INFO","fields":{"message":"Published Bitcoin transaction","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","kind":"lock"}}
{"timestamp":"2023-09-06T21:57:51.922484Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is locked"}}
{"timestamp":"2023-09-06T21:57:52.139808Z","level":"DEBUG","fields":{"message":"Found relevant Bitcoin transaction","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","status":"unseen"}}
{"timestamp":"2023-09-06T21:57:52.140108Z","level":"INFO","fields":{"message":"Waiting for Alice to lock Monero"}}
{"timestamp":"2023-09-06T21:58:54.617220Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"985bd492ea97788277a6208ee93a270152e3a40c6a916e0b40c0100fe73ef629","new_status":"in mempool","old_status":"unseen"}}
{"timestamp":"2023-09-06T23:30:45.7991901Z","level":"INFO","fields":{"message":"Logging initialized to C:\\Users\\desgr\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\logs"}}
{"timestamp":"2023-09-06T23:30:45.7995907Z","level":"DEBUG","fields":{"message":"Using existing sqlite database."}}
{"timestamp":"2023-09-06T23:30:45.8010298Z","level":"DEBUG","fields":{"message":"Reading in seed from C:\\Users\\desgr\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\seed.pem"}}
{"timestamp":"2023-09-06T23:30:47.3931887Z","level":"DEBUG","fields":{"message":"RPC exec path: C:\\Users\\desgr\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\monero\\monero-wallet-rpc.exe"}}
{"timestamp":"2023-09-06T23:30:48.4429574Z","level":"DEBUG","fields":{"message":"RPC version output: Monero 'Fluorine Fermi' (v0.18.1.2-release)\r\n"}}
{"timestamp":"2023-09-06T23:30:48.4433043Z","level":"DEBUG","fields":{"message":"Starting monero-wallet-rpc","port":"58036"}}
{"timestamp":"2023-09-06T23:30:55.7255908Z","level":"DEBUG","fields":{"message":"Opened Monero wallet","monero_wallet_name":"swap-tool-blockchain-monitoring-wallet"}}
{"timestamp":"2023-09-06T23:30:57.7658212Z","level":"DEBUG","fields":{"message":"Network layer initialized","peer_id":"12D3KooWF1REzmMKvoXv1DpKcAyzA4pMDXx6N4qkDknpqvpCvQYC"}}
{"timestamp":"2023-09-06T23:30:57.7669133Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2023-09-06T23:30:57.7712395Z","level":"WARN","fields":{"message":"Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists.: JSON-RPC request failed with code -1: Wallet already exists."}}
{"timestamp":"2023-09-06T23:30:57.7712678Z","level":"INFO","fields":{"message":"Falling back to trying to open the the wallet if it already exists","wallet_file_name":"9f442c10-4925-4a9a-9764-5174e786e694"}}
{"timestamp":"2023-09-06T23:30:58.3361953Z","level":"INFO","fields":{"message":"Connected to Alice at /dns4/beta.unstoppableswap.net/tcp/9939/p2p/12D3KooWMiriru5viqde3BMFLTqPur8Yrjpp4ULFc76ubQLfuYYX"}}

**Comment by weeb042069** [comment]
I am going to close this because I was able to use the fix found in another github to solve the issues.
Here is a link the the post https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147

**Comment by binarybaron** [comment]
Updating the GUI to `0.5.1` would also fix the issue

**Comment by NoUsername1337** [comment]
not fixed in 0.5.1 commented on other thread. will post logs
