### ISSUE TITLE
Swap is "unfinished" after being stuck at redeeming XMR - Potentially urgent illicit refund implications

### ISSUE THREAD

**Issue by Beliak-Legend** [UnstoppableSwap/unstoppableswap-gui#164]
## Expected Behavior

Monero goes to my wallet after my partner in the swap redeems their BTC.

## Current Behavior

After being stuck at the "Redeeming XMR" phase for ~6 hours, UnstoppableSwap created a new wallet with keys that I had to manually access and transfer by using them to create a new wallet in Monero GUI.

I noticed a few others had this problem, and I was able to follow the workaround steps provided to others having this issue and resolve the problem manually by using the swap tool in Powershell.

What is concerning however, is that after I went through this process of finding and transferring the misplaced XMR, it still stated that I had not redeemed the XMR on the UnstoppableSwap GUI, AND I WAS ELIGIBLE FOR A REFUND OF MY BTC. I of course did not utilize this option, but if a bad actor was able to replicate this issue during a huge swap, there could be dire consequences. Even now, it continues to say I have not redeemed the XMR yet.

## Steps to Reproduce

1. Initiated a Swap with Swap Provider /ip4/45.138.50.29/tcp/9939.

2. Swap proceeded as normal, until the final stage of redeeming my newly acquired XMR. The estimated wait time of 2 minutes was far exceeded, and it continued attempting to redeem the XMR for about 6 hours before stopping with an error.

3. Error notifications "Swap xxxxxxxx-xxxx... is unfinished" and "You have 1 unfinished swaps" presented themselves on screen.

4. After reading through other bug reports, I attempted the workaround with the swap tool in Powershell described above.

5. I successfully located the newly created view and spend keys, and used them to set up a new wallet, which I then transferred to my originally intended destination wallet (the one I tried to have my swap deposited to).

6. After the appropriate amount of time passed, the swap "State" was still on "Bitcoin has been redeemed" and I was eligible for a refund of my BTC, even though I had since manually located and transferred the XMR.

## Possible Solution (Not obligatory)

Unfortunately I'm not sure how to fix it, I don't know why the XMR didn't go to my intended wallet. I wanted to bring attention to this issue before people wrongfully start to lose BTC.

## Your Environment

- Node version : UnstoppableSwap 0.5.2
- Operating System and version : Windows 10 Home 10.0.19045 Build 19045

**Comment by binarybaron** [comment]
Thanks for the bug report. Please post the logs of you swap if you are comfortable with that. Feel free to censor private information (e.g Bitcoin amounts).

This bug is known and we're still looking for a fix... An illicit refund is definitely not possible because the Bitcoin have already been redeemed. They can't be spent again.
