### ISSUE TITLE
JSON-RPC request failed with code -38: no connection to daemon

### ISSUE THREAD

**Issue by herrsocke** [UnstoppableSwap/unstoppableswap-gui#165]
## Expected Behavior

XMR should have been redeemable

## Current Behavior

The state is stuck on redeeming your XMR

## Steps to Reproduce

JSON-RPC request failed with code -38: no connection to daemon

I have a stable internet connection othwise

- Node version : 
- Operating System and version : Win 11

**Comment by sitkonen** [comment]
I just had the same problem. Any suggestion how to fix this?

**Comment by herrsocke** [comment]
No and in 2 Hours I will loose all my funds.

**Comment by sitkonen** [comment]
> No and in 2 Hours I will loose all my funds. Manual refund is deactivated for me.

I managed to get my monero using command line. 
In C:\Users\*********\AppData\Local\Programs\unstoppableswap-gui\resources\bin there is swap.exe. Use command swap -d C:\Users\*********\AppData\Roaming\xmr-btc-swap\cli\ monero-recovery --swap-id your_swap_id_here (check unstoppableswap for that). It should give you Monero wallet address, view key AND spend key. Now restore the wallet somewhere using that information (i used cake wallet on android). Now you have wallet with your monero.

**Comment by herrsocke** [comment]
No transactions / balance is shown in that value

**Comment by binarybaron** [comment]
First please try upgrading the GUI and attempt to resume the swap.

If that doesn't work follow the steps described here: https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/154#issuecomment-1683737539

**Comment by herrsocke** [comment]
The GUI was at 0.5.2.
I also tried ./swap monero-recovery --swap-id YOUR_SWAP_ID

**Comment by herrsocke** [comment]
Also why is the manual refund button deactivated in the GUI?

**Comment by binarybaron** [comment]
> Also why is the manual refund button deactivated in the GUI?

It's not possible to refund the monero as they have already been spent by the swap provider. You need to redeem the monero as described in the linked comment.
What issue did you encounter?

**Comment by herrsocke** [comment]
I did this:
https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/162#issuecomment-1748662122

but the monero wallet was empty.

**Comment by binarybaron** [comment]
Please try lowering the restore height in the GUI. It'll make sure the wallet actually scans the relevant transactions and can display the correct balance.

**Comment by herrsocke** [comment]
Thank you so much, this worked! All funds have been recoverd.

**Comment by binarybaron** [comment]
Good to hear! What version of the GUI were you running if I may ask?
We implemented some changes in release `0.5.2' but it seems that the issue was not resolved for everyone.

**Comment by herrsocke** [comment]
I was using 0.5.2

**Comment by binarybaron** [comment]
This issue has been fixed in the latest pre-release of the GUI: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.0

Download it and resume the swap. The Monero will be redeemed successfully.
