### ISSUE TITLE
Issue withdrawing funds from Unstoppableswap

### ISSUE THREAD

**Issue by Rplywood** [UnstoppableSwap/unstoppableswap-gui#166]
Withdrawn funds not received. I am an absolute novice.

I sent approx .015 BTC to my unstoppableswap App. The funds arrived in the App. I tried to send the funds as Monero to my Monero wallet. The swap failed: 
"Caused by:
0: Failed to deserialize bytes into message using CBOR
1: EOF while parsing a value"

I clicked 'withdraw' to return the funds to my coinspot wallet. It would not accept the address because it was not a Bech32 address. I used an online converter to change my wallet address to an address beginning "bc1...". I inputted that new address and clicked "withdraw"

Unstoppableswap shows the funds as having been withdrawn. However, those funds have not reappeared in my Coinspot wallet. 

Help please

**Comment by binarybaron** [comment]
I'm really sorry but you have most likely been scammed by that online converter site you used. It's not possible to convert between different types of bitcoin addresses. The "converter" stole your funds.
Do you have a link?

**Comment by Rplywood** [comment]
Yes it was https://blockchain-academy.hs-mittweida.de/bech32-tool/

**Comment by binarybaron** [comment]
Okay the tool you used is not malicious but you still won't be able to recover the funds (as of my knowledge). The funds were sent to the address you specified (you can check on any public blockchain explorer) but you do not have the private keys to that address.
You can investigate yourself further by asking for help in a Bitcoin Dev forum or something of the sorts. They might have more knowledge regarding the specifics of the bitcoin address protocol. There is a minuscule chance that I'm missing something here.

**Comment by binarybaron** [comment]
I'm closing this. If you need to, feel free to reopen!
