### ISSUE TITLE
Help PLease

### ISSUE THREAD

**Issue by NOBULLSHIT13** [UnstoppableSwap/unstoppableswap-gui#167]
## Summary

<!-- What do you need help with? --i COMPLETED A SWAP AND RECIVED NOTHING IN RETURN WHAT HAPPEN TO MY BITCOIN OR xmr THAT I WAS SUPPOSED TO GET.
![image](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/151970182/46f91af5-1180-4ef3-a98a-2e827fa02c15)

**Comment by binarybaron** [comment]
What's the issue?
