### ISSUE TITLE
Need help  malicious actor?

### ISSUE THREAD

**Issue by Needhelpppop** [UnstoppableSwap/unstoppableswap-gui#168]
Tried to swap btc to monero now it says “be careful”
The swap provider has taken a long time to lock their monero. This might mean that:
They are a malicious actor
There is a technical issue that prevents them from locking their funds

- Operating System and version : windows 10 64bits

what do I do? Is the program still working?

**Comment by Needhelpppop** [comment]
IT says they refunded the btc etc... 
https://blockchair.com/bitcoin/transaction/dffa96b426e46a37a4105a3a4925c1d6b3e5f3f5b9144af3998d6ce180f3cb49

I just checked my wallet adress through mail and it is the exact same one I entered.
How is it not on my wallet omg.... I can cry FR now omg... 

Did this 3 times:
first time my monero went to a random wallet which i had to get reget the keys for worked only took my 6 hours
second time everything went flawless..
third time now this!!! wtf where is my money!!

**Comment by binarybaron** [comment]
Can you post the logs of your swap? (If running turn in debug and click copy logs, otherwise go to History tab, expand the row and click "View Logs")
