### ISSUE TITLE
BTC refunded but with a very low fee?

### ISSUE THREAD

**Issue by IncreasinglyBored** [UnstoppableSwap/unstoppableswap-gui#169]
Hi,

I tried to swap BTC days ago, unfortunately it did not work out. Not too bad, can happen.

Although my problem now is, that you apparently refund the BTC with a very low fee (in my case 19 sat/b)

Since the fees are currently way higher, I doubt this TX would get a confirmation anytime soon. Could you perhaps increase the fee?

Not that I've a problem with waiting, but I figure this won't get a confirm in the next 14 days, and possibly just drop out of mempool, so you see my concerns.

**Comment by binarybaron** [comment]
Do you have access to the receiving wallet?

If so, I'd advise you to try getting the transaction confirmed using Child-Pays-For-Parent (https://www.exodus.com/support/article/1376-what-is-a-child-pays-for-parent-transaction#:~:text=%2DFor%2DParent%3F-,What%20is%20a%20Child%2DPays%2DFor%2DParent%20transaction%3F,(the%20%E2%80%9Cchild%E2%80%9D). Essentially you are spending the unconfirmed funds using a transaction with a high fee to incentivize miners to include the refund transaction in a block.
