### ISSUE TITLE
XMR not redeemed, not able to cancel. 

### ISSUE THREAD

**Issue by EtasAnonymous** [UnstoppableSwap/unstoppableswap-gui#170]
Hey, I'm trying to complete my swap but it won't complete redeeming the XMR. I only have 6 hours left to complete the transaction but the cancel & refund button is greyed out. Doesn't seem like there's anything I can do here. I have to just lose these funds entirely? 

Please help.

**Comment by binarybaron** [comment]
I'm sorry for the issue. Your funds are safe.

See https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247 for a fix.

**Comment by binarybaron** [comment]
> > See [#147 (comment)](https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247) for a fix.
> 
> That worked, thank you! What is the cause of the problem though - a network issue?

I'm still unsure. Would you mind sharing the logs of your swap? It will help me debug the issue (History Tab -> Expand your swap -> View log). The logs of the `monero-wallet-rpc` would also be helpful (Can be found here on Windows `C:\Users\YOUR_USERNAME\AppData\Roaming\xmr-btc-swap\cli\mainnet\monero` )

**Comment by mdhoney** [comment]
> I'm still unsure. Would you mind sharing the logs of your swap? It will help me debug the issue (History Tab -> Expand your swap -> View log). The logs of the `monero-wallet-rpc` would also be helpful (Can be found here on Windows `C:\Users\YOUR_USERNAME\AppData\Roaming\xmr-btc-swap\cli\mainnet\monero` )

Would happily share the logs, I see several TXIDs and wallet IDs in there though.... Is there an easy way to sanitize these logs?

**Comment by binarybaron** [comment]
You'll have to sanitize them manually unfortunately. If you prefer to you can also send them to me privately on Matrix @binarybaron:matrix.org
