### ISSUE TITLE
stuck on redeeming xmr

### ISSUE THREAD

**Issue by sdot112** [UnstoppableSwap/unstoppableswap-gui#172]
was swapping my btc an on the final step (4.redeeming your xmr) it is taking forever an just keeps failing.

pls help this is annoying as fuck

im using linux debian & v.0.5.2

**Comment by binarybaron** [comment]
I'm sorry for the issue. Your funds are safe.

See https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247 for a fix.
