### ISSUE TITLE
Swap failed. Please advise

### ISSUE THREAD

**Issue by gpucool17** [UnstoppableSwap/unstoppableswap-gui#178]
## Expected Behavior

I was expecting to receive XMR

## Current Behavior

Swap failed on the last step. It looks like server/swap provider is no longer listed. Did I get scammed? Or is there a way to get the XMR or get the BTC back?

Here is some of the debug output. Not sure if it will be helpful.

{"timestamp":"2024-02-07T10:53:56.9722999Z","level":"DEBUG","fields":{"message":"Advancing state","state":"btc is redeemed"}}
{"timestamp":"2024-02-07T10:55:09.0019124Z","level":"WARN","fields":{"message":"Lost connection to Alice at /ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o, cause: Connection error: I/O error: connection is closed"}}
{"timestamp":"2024-02-07T10:55:11.0150327Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:11.0150727Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:16.3905578Z","level":"WARN","fields":{"message":"Failed to dial Alice: An error occurred while negotiating the transport protocol(s) on a connection: [(\"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o\", Other(Custom { kind: Other, error: Other(A(A(Custom { kind: Other, error: A(Custom { kind: ConnectionRefused, error: GeneralSocksServerFailure }) }))) }))]."}}
{"timestamp":"2024-02-07T10:55:16.3905895Z","level":"INFO","fields":{"message":"Next redial attempt in 5s"}}
{"timestamp":"2024-02-07T10:55:22.0545342Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:22.0545794Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:22.6665718Z","level":"WARN","fields":{"message":"Failed to dial Alice: An error occurred while negotiating the transport protocol(s) on a connection: [(\"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o\", Other(Custom { kind: Other, error: Other(A(A(Custom { kind: Other, error: A(Custom { kind: ConnectionRefused, error: ConnectionRefused }) }))) }))]."}}
{"timestamp":"2024-02-07T10:55:22.6665995Z","level":"INFO","fields":{"message":"Next redial attempt in 6s"}}
{"timestamp":"2024-02-07T10:55:29.558742Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:29.5587944Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:30.3686049Z","level":"WARN","fields":{"message":"Failed to dial Alice: An error occurred while negotiating the transport protocol(s) on a connection: [(\"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o\", Other(Custom { kind: Other, error: Other(A(A(Custom { kind: Other, error: A(Custom { kind: ConnectionRefused, error: ConnectionRefused }) }))) }))]."}}
{"timestamp":"2024-02-07T10:55:30.3686318Z","level":"INFO","fields":{"message":"Next redial attempt in 11s"}}
{"timestamp":"2024-02-07T10:55:41.9883729Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:41.9884117Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:42.3442083Z","level":"WARN","fields":{"message":"Failed to dial Alice: An error occurred while negotiating the transport protocol(s) on a connection: [(\"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o\", Other(Custom { kind: Other, error: Other(A(A(Custom { kind: Other, error: A(Custom { kind: ConnectionRefused, error: ConnectionRefused }) }))) }))]."}}
{"timestamp":"2024-02-07T10:55:42.344234Z","level":"INFO","fields":{"message":"Next redial attempt in 17s"}}
{"timestamp":"2024-02-07T10:55:57.6561161Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":829346}}
{"timestamp":"2024-02-07T10:55:57.8401854Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cb1554eab79ed40ad49137f1862d8e27adb4e9e25c45321f47dae439858e992c","new_status":"confirmed with 1 blocks","old_status":"in mempool"}}
{"timestamp":"2024-02-07T10:55:57.8402133Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"8363c2ecd2b73ad2359b54cf324bdba5cba1b6ba3682af5b90421734d345b641","new_status":"confirmed with 31 blocks","old_status":"confirmed with 30 blocks"}}
{"timestamp":"2024-02-07T10:55:59.4526042Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:59.452654Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:55:59.8271037Z","level":"WARN","fields":{"message":"Failed to dial Alice: An error occurred while negotiating the transport protocol(s) on a connection: [(\"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o\", Other(Custom { kind: Other, error: Other(A(A(Custom { kind: Other, error: A(Custom { kind: ConnectionRefused, error: ConnectionRefused }) }))) }))]."}}
{"timestamp":"2024-02-07T10:55:59.8271343Z","level":"INFO","fields":{"message":"Next redial attempt in 31s"}}
{"timestamp":"2024-02-07T10:56:31.009998Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:56:31.0100427Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:56:31.250437Z","level":"WARN","fields":{"message":"Failed to dial Alice: An error occurred while negotiating the transport protocol(s) on a connection: [(\"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o\", Other(Custom { kind: Other, error: Other(A(A(Custom { kind: Other, error: A(Custom { kind: ConnectionRefused, error: ConnectionRefused }) }))) }))]."}}
{"timestamp":"2024-02-07T10:56:31.2504665Z","level":"INFO","fields":{"message":"Next redial attempt in 34s"}}
{"timestamp":"2024-02-07T10:56:58.1983632Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":829347}}
{"timestamp":"2024-02-07T10:56:58.3942683Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"8363c2ecd2b73ad2359b54cf324bdba5cba1b6ba3682af5b90421734d345b641","new_status":"confirmed with 32 blocks","old_status":"confirmed with 31 blocks"}}
{"timestamp":"2024-02-07T10:56:58.3943009Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cb1554eab79ed40ad49137f1862d8e27adb4e9e25c45321f47dae439858e992c","new_status":"confirmed with 2 blocks","old_status":"confirmed with 1 blocks"}}
{"timestamp":"2024-02-07T10:57:05.7024083Z","level":"DEBUG","fields":{"message":"Dialling Alice at 12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:57:05.7024536Z","level":"DEBUG","fields":{"message":"Establishing connection through Tor proxy","address":"/ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T10:57:05.9320063Z","level":"DEBUG","fields":{"message":"Connection through Tor established"}}
{"timestamp":"2024-02-07T10:57:06.9842729Z","level":"INFO","fields":{"message":"Connected to Alice at /ip4/185.165.169.235/tcp/9939/p2p/12D3KooWQVsDswChwnCJrYVSeuLdZoxL4mufdsogNxtZbSMUb81o"}}
{"timestamp":"2024-02-07T11:03:08.9148473Z","level":"DEBUG","fields":{"message":"Got notification for new block","block_height":829348}}
{"timestamp":"2024-02-07T11:03:09.0830806Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"cb1554eab79ed40ad49137f1862d8e27adb4e9e25c45321f47dae439858e992c","new_status":"confirmed with 3 blocks","old_status":"confirmed with 2 blocks"}}
{"timestamp":"2024-02-07T11:03:09.0831112Z","level":"DEBUG","fields":{"message":"Bitcoin transaction status changed","txid":"8363c2ecd2b73ad2359b54cf324bdba5cba1b6ba3682af5b90421734d345b641","new_status":"confirmed with 33 blocks","old_status":"confirmed with 32 blocks"}}
Error: Failed to complete swap

Caused by:
    0: JSON-RPC request failed with code -38: no connection to daemon
    1: JSON-RPC request failed with code -38: no connection to daemon

1.

2.

3.

4.

## Your Environment

- Node version : 0.5.3
- Operating System and version : Windows 10 Pro N

**Comment by binarybaron** [comment]
Known bug. I've messaged the user privately

https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247
