### ISSUE TITLE
"Failed to get transaction from daemon"

### ISSUE THREAD

**Issue by d9o8m7** [UnstoppableSwap/unstoppableswap-gui#179]
## Expected Behavior
Everything was going smoothly, all Swaps and Locks were fine.
I was in the final step 4 to receive the swap.
But an error starter to prompt:

![ERR_Reddem](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/62662026/c4f7ef0e-be86-4510-9f7e-a5a3ead0c664)

1."level":"WARN","fields":{"message":"`monero-wallet-rpc` failed to fetch transaction, may need to be restarted"

2."level":"DEBUG","fields":{"message":"Failed to get transaction from daemon","data":"None"}}

3.Error: Failed to complete swap

Caused by:
    0: JSON-RPC request failed with code -38: no connection to daemon
    1: JSON-RPC request failed with code -38: no connection to daemon

## MY ENV
- Node version : v20.1.0
- Operating System and version : macOS Catalina 10.15.7 19H2026 x86_64
- Host: MacBookPro9,2
- Kernel: 19.6.0

**Comment by d9o8m7** [comment]
Done! Finally, the Transaction went through with some Retry's

**Comment by absywabsy** [comment]
Hello, how did you retry? The only option is "Done"
