### ISSUE TITLE
XMR -> BTC It's woking?

### ISSUE THREAD

**Issue by vkornilyev1988** [UnstoppableSwap/unstoppableswap-gui#181]
Please tell me if I can deploy my backend server, is it mentioned somewhere in the project? In order to be able to atomically buy BTC for monera. Either this is not possible or there is not even a theoretical way to do this and this project is only for buying Monero for BTC. How about the reverse order? I would like to know whether it works or not not BTC->xmr but XMR-btc?

**Comment by binarybaron** [comment]
It's difficult but possible. This is not really meant to be used for buying Bitcoin one time.

https://github.com/comit-network/xmr-btc-swap/blob/master/docs/asb/README.md
