### ISSUE TITLE
What should I do? Did the provider steal it?

### ISSUE THREAD

**Issue by Jymmybelsher** [UnstoppableSwap/unstoppableswap-gui#185]
This transfer was not completed at the 4th stage of "Redeeming your XMR" and was interrupted with the error "Error: JSON-RPC request failed with code -38: no connection to daemon" provider"/ip4/45.138.50.29/tcp/9939"

BTC Sender Address: bc1qljlszpa4**********************
XMR Recipient Address: 46kWnWtoXn1LECzvUWxm5JhyvbfvLXaxXBKaZgRUhm3W*****************************************
Provider: /ip4/45.138.50.29/tcp/9939

Screenshots of the program (some areas are blurred just in case)
![Screenshot_3](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/159011985/32c512d3-39ad-4344-aeca-ac8cc1491528)

The provider "45.138.50.29" stole 3.168 XMR beware.
![Screenshot_4](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/161569597/49797c01-247c-4244-85ca-05282d162f6e)

Swap is still possible, but the button never leads to anything other than an error, the same error has been happening for a week now.

How do I continue? Is this a lottery? Please help me jymmybelsher94@gmail.com

**Comment by Jymmybelsher** [comment]
I also keep trying to return something, the option from the comment [147#](https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247) to get the keys did not work, there are no coins in the account.

**Comment by scramblr** [comment]
This is unbelievable. Has it still not been resolved? Is this really a thing that can happen??

**Comment by Jymmybelsher** [comment]
Yes, the problem is still not solved, I don’t know what to do next, no one has contacted me yet for a solution, the provider is silent and I don’t have his contact information, it seems the coins are stuck, now I’m afraid to use this software , despite the fact that 2 out of 3 exchanges were successful. 

> This is unbelievable. Has it still not been resolved? Is this really a thing that can happen??

**Comment by Jymmybelsher** [comment]
I am open to dialogue, if the provider "45.138.50.29" or another leading member of the team requests logs or additional information, I will provide it immediately. Please contact me: [jymmybelsher94@gmail.com](mailto:jymmybelsher94@gmail.com)

**Comment by binarybaron** [comment]
I can assure you that the coins are in the wallet you have restored. Please try adjusting the restore height. This issue *cannot* result in the loss of your funds.

**Comment by Jymmybelsher** [comment]
> I can assure you that the coins are in the wallet you have restored. Please try adjusting the restore height. This issue _cannot_ result in the loss of your funds.

I'll try again

**Comment by Jymmybelsher** [comment]
I managed to solve my problem, it takes a long time to download the blockchain, be sure to use key recovery and wait for the blockchain to download

**Comment by scramblr** [comment]
I think it's important to be clear here: You, in the end, received your XMR/Monero via UnstoppableSwap, and this was just a minor configuration issue, not a theft. Correct?

**Comment by Jymmybelsher** [comment]
> I think it's important to be clear here: You, in the end, received your XMR/Monero via UnstoppableSwap, and this was just a minor configuration issue, not a theft. Correct?

Yes, the problem has been completely resolved, I have no complaints, all XMR coins have been received by me
