### ISSUE TITLE
can't redeem Monero GUI on MACOS

### ISSUE THREAD

**Issue by rnrkrft** [UnstoppableSwap/unstoppableswap-gui#190]
From log:

{"timestamp":"2024-03-25T05:57:41.032222Z","level":"INFO","fields":{"message":"Logging initialized to /Users/rnrkrft/Library/Application Support/xmr-btc-swap/cli/mainnet/logs"}}
{"timestamp":"2024-03-25T05:57:41.032359Z","level":"DEBUG","fields":{"message":"Using existing sqlite database."}}
{"timestamp":"2024-03-25T05:57:41.034302Z","level":"DEBUG","fields":{"message":"Reading in seed from /Users/rnrkrft/Library/Application Support/xmr-btc-swap/cli/mainnet/seed.pem"}}
{"timestamp":"2024-03-25T05:57:41.034339Z","level":"DEBUG","fields":{"message":"Initializing bitcoin wallet"}}
{"timestamp":"2024-03-25T05:57:41.180140Z","level":"DEBUG","fields":{"message":"Syncing bitcoin wallet"}}
{"timestamp":"2024-03-25T05:57:41.641855Z","level":"DEBUG","fields":{"message":"RPC exec path: /Users/rnrkrft/Library/Application Support/xmr-btc-swap/cli/mainnet/monero/monero-wallet-rpc"}}
{"timestamp":"2024-03-25T05:57:42.907964Z","level":"DEBUG","fields":{"message":"RPC version output: Monero 'Fluorine Fermi' (v0.18.1.2-release)\n"}}
{"timestamp":"2024-03-25T05:58:12.910883Z","level":"DEBUG","fields":{"message":"Failed to connect to Monero daemon","err":"Failed to send request to get_info endpoint","daemon":"xmr-node.cakewallet.com:18081"}}
{"timestamp":"2024-03-25T05:58:15.911130Z","level":"DEBUG","fields":{"message":"Found available Monero daemon","daemon":"nodex.monerujo.io:18081"}}
{"timestamp":"2024-03-25T05:58:15.911251Z","level":"DEBUG","fields":{"message":"Starting monero-wallet-rpc","daemon_address":"nodex.monerujo.io:18081","port":"51454"}}
{"timestamp":"2024-03-25T05:58:22.523568Z","level":"DEBUG","fields":{"message":"Opened Monero wallet","monero_wallet_name":"swap-tool-blockchain-monitoring-wallet"}}
{"timestamp":"2024-03-25T06:53:04.905706Z","level":"INFO","fields":{"message":"Logging initialized to /Users/rnrkrft/Library/Application Support/xmr-btc-swap/cli/mainnet/logs"}}
{"timestamp":"2024-03-25T06:53:04.905773Z","level":"DEBUG","fields":{"message":"Using existing sqlite database."}}
{"timestamp":"2024-03-25T06:53:04.908136Z","level":"DEBUG","fields":{"message":"Reading in seed from /Users/rnrkrft/Library/Application Support/xmr-btc-swap/cli/mainnet/seed.pem"}}
{"timestamp":"2024-03-25T06:53:04.908163Z","level":"DEBUG","fields":{"message":"Initializing bitcoin wallet"}}
{"timestamp":"2024-03-25T06:53:05.031594Z","level":"DEBUG","fields":{"message":"Syncing bitcoin wallet"}}
{"timestamp":"2024-03-25T06:53:05.440697Z","level":"DEBUG","fields":{"message":"RPC exec path: /Users/rnrkrft/Library/Application Support/xmr-btc-swap/cli/mainnet/monero/monero-wallet-rpc"}}
{"timestamp":"2024-03-25T06:53:06.710157Z","level":"DEBUG","fields":{"message":"RPC version output: Monero 'Fluorine Fermi' (v0.18.1.2-release)\n"}}
{"timestamp":"2024-03-25T06:53:36.711884Z","level":"DEBUG","fields":{"message":"Failed to connect to Monero daemon","err":"Failed to send request to get_info endpoint","daemon":"xmr-node.cakewallet.com:18081"}}

**Comment by binarybaron** [comment]
See this comment https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247

**Comment by binarybaron** [comment]
Great! Unfortuntely theres no way to fix that at the moment. You can just ignore it. Maybe we will add a button to hide a swap in the future.
