### ISSUE TITLE
swap failed redeem Monero

### ISSUE THREAD

**Issue by rnrkrft** [UnstoppableSwap/unstoppableswap-gui#193]
The transaction fails after redeem the Bitcoin as it tried to redeem Monero. Can't get pass 4 confitmations. 
I got the Monero manual, but the History shows the swap 6fabe42b-fe8f-4e67-8e12-8c32145728ef is unfinished.

I use 

UnstoppableSwap GUI 
Version 0.5.3 (0.5.3)

on MacPro with MacOS Sonoma 
![Bildschirmfoto 2024-04-11 um 22 41 54](https://github.com/UnstoppableSwap/unstoppableswap-gui/assets/6118278/47c5a64c-037a-4f81-a37f-d5c364cc0115)

**Comment by binarybaron** [comment]
Please see this comment https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/190#issuecomment-2018132638

Has your swap gone through?

**Comment by binarybaron** [comment]
This issue has been fixed in the latest pre-release of the GUI: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.0

Download it and resume the swap. The Monero will be redeemed successfully.
