### ISSUE TITLE
Lost money through refund UnstoppableSwap

### ISSUE THREAD

**Issue by junky808** [UnstoppableSwap/unstoppableswap-gui#197]
## Expected Behavior

Hey there I desperately need some help. So I tried to make a swap on Unstoppable and it didn't work out so after 12 hours, it said "Bitcoin has been refunded" but when I went to look in my wallet, it was refunded for 30$ less than I had sent. I don't know what to do any help would be really appreciated.

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- Operating System and version :

**Comment by binarybaron** [comment]
Bitcoin fees are quite high. There is nothing we can really do about it unfortunately. There are 3 transactions required in total (lock, cancel, refund) to refund.
I'd advise you to monitor the network and swap when fees are as low as possible.
