### ISSUE TITLE
Can't redeem XMR  caused by Json-rpc request failed with code -38 : no connection to daemon  Mac sonoma 14.2.1

### ISSUE THREAD

**Issue by wakaka33** [UnstoppableSwap/unstoppableswap-gui#201]
## Expected Behavior

Redeem XMR should have success and i should have get my xmr

## Current Behavior

Can't redeem XMR  caused by Json-rpc request failed with code -38 : no connection to daemon  ( I have looked for solutions but most of them are for windows) I  using MacOS Sonoma 14.2.1 , please help me in retrieving the fund as i really needed the money. Thanks in advance!

## Your Environment
MacOS Sonoma 14.2.1

UnstopapbleSwap 0.5.3
- Operating System and version : MacOS Sonoma 14.2.1

**Comment by wakaka33** [comment]
Please help me if any of you guys have a solution to this ㅜㅜ

**Comment by binarybaron** [comment]
Hey,

thanks for reporting this. It's a known issue but there's no risk of loosing your funds. You can take your time.
You can do one of three things:
1. Try resuming the swap a few more times. This sometimes does the trick.
2. Follow the instructions here: https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/147#issuecomment-1647742247 to manually redeem the funds (I recommend this one)
3. Wait a few weeks for the new version to be released which will hopefully fix this issue (Unlikely you'll want to choose this one)

**Comment by binarybaron** [comment]
This issue has been fixed in the latest pre-release of the GUI: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.0

Download it and resume the swap. The Monero will be redeemed successfully.
