### ISSUE TITLE
daemon has stopped

### ISSUE THREAD

**Issue by dgrey-cyber** [UnstoppableSwap/unstoppableswap-gui#205]
## Your Environment

- Operating System:
- GUI Version:

**Comment by binarybaron** [comment]
Please go to the `Help` tab, copy the `Swap Daemon Logs` by clicking on the small copy icon and paste it here.

**Comment by binarybaron** [comment]
I'm going to close this. Please reopen once if the issue persist and you are able to provide us with the logs.
