### ISSUE TITLE
Signatures to verify binaries?

### ISSUE THREAD

**Issue by AngeloMetal** [UnstoppableSwap/unstoppableswap-gui#211]
I want to verify UnstoppableSwap. Are there any signatures anywhere? There are none in the release page, and neither in unstoppableswap.net.

**Comment by binarybaron** [comment]
I have GPG signed the latest 0.6.2 release: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.2. See the release notes on where to find my signing key and how to verify the validity of the release files.

**Comment by Silarous** [comment]
> I have GPG signed the latest 0.6.2 release: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.2. See the release notes on where to find my signing key and how to verify the validity of the release files.

I'm getting a bad signature report when verifying the release.

gpg: Signature made 7/26/2024 1:54:42 AM Central Daylight Time
gpg:                using EDDSA key 35A844D7F4B55BC44E180FF199B75D3E1476A26E
gpg: BAD signature from "binarybaron <binarybaron@unstoppableswap.net>" [full]

**Comment by binarybaron** [comment]
> > I have GPG signed the latest 0.6.2 release: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.2. See the release notes on where to find my signing key and how to verify the validity of the release files.
> 
> I'm getting a bad signature report when verifying the release.
> 
> gpg: Signature made 7/26/2024 1:54:42 AM Central Daylight Time
> gpg:                using EDDSA key 35A844D7F4B55BC44E180FF199B75D3E1476A26E
> gpg: BAD signature from "binarybaron <binarybaron@unstoppableswap.net>" [full]

Which signature did you try verify?

**Comment by Silarous** [comment]
UnstoppableSwap-0.6.3.AppImage with UnstoppableSwap-0.6.3.AppImage.asc using the signature found at https://unstoppableswap.net/binarybaron.asc

**Comment by Silarous** [comment]
> > > I have GPG signed the latest 0.6.2 release: https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.2. See the release notes on where to find my signing key and how to verify the validity of the release files.
> > 
> > 
> > I'm getting a bad signature report when verifying the release.
> > gpg: Signature made 7/26/2024 1:54:42 AM Central Daylight Time
> > gpg:                using EDDSA key 35A844D7F4B55BC44E180FF199B75D3E1476A26E
> > gpg: BAD signature from "binarybaron [binarybaron@unstoppableswap.net](mailto:binarybaron@unstoppableswap.net)" [full]
> 
> Which signature did you try verify? (which file)

UnstoppableSwap-0.6.3.AppImage with UnstoppableSwap-0.6.3.AppImage.asc using the signature found at https://unstoppableswap.net/binarybaron.asc

**Comment by KayTX** [comment]
Bad signature still exists for "UnstoppableSwap-0.6.3.AppImage".
Issue should be reopened.
