### ISSUE TITLE
Swap stuck at redeem monero stage - please help!

### ISSUE THREAD

**Issue by tomvanno** [UnstoppableSwap/unstoppableswap-gui#216]
## Explain what you did

Entered swap for about 1.5 BTC to XMR, entered both BTC and XMR receipt addresses, started swap.

Received error message on redeem monero phase

## Which state is your swap in?

BtcRedeemed

## What is the problem?

Getting an error at the reedem monero stage 'the swap-cli process has exited with the exit code 1 but the swap has not been completed yet. The current state is BtcRedeemed. Please check the logs below for more information. You might have to manually take some action.

In the log at the bottom it says:
'JSON-RPC request failed with code -38: no connection to daemon'

In debug seeing a lot of:
 'failed to get transaction from daemon' 'monero-wallet-rpc failed to fetch transaction, may need to be restarted'

## Your Environment

- Operating System: Mac OS Catalina 10.15.7
- GUI Version: 0.5.3

Thank you in advance - please let me know if I can provide any other bits of info.

**Comment by binarybaron** [comment]
You need to update to the latest GUI version. Especially when swapping such large amounts. This issue has been fixed in newer versions.
