### ISSUE TITLE
Swap daemon won't start (error : "The swap daemon has stopped unexpectedly")

### ISSUE THREAD

**Issue by razlebol** [UnstoppableSwap/unstoppableswap-gui#221]
I get the error "The swap daemon has stopped unexpectedly"
Any idea what could be the issue. It worked correctly a few weeks ago

## Current Behavior

{"timestamp":"2024-09-25T15:00:07.210271Z","level":"INFO","fields":{"message":"Logging initialized to /Users/xxx/Library/Application Support/xmr-btc-swap/cli/mainnet/logs"}}
{"timestamp":"2024-09-25T15:00:07.210329Z","level":"DEBUG","fields":{"message":"No seed file found, creating at /Users/xxx/Library/Application Support/xmr-btc-swap/cli/mainnet/seed.pem"}}
"Error: "
"Failed to initialize Bitcoin wallet"
"Caused by:"
"    0: Failed to subscribe to header notifications"
"    1: Made one or multiple attempts, all errored:"
"       \t- invalid peer certificate contents: invalid peer certificate: CertNotValidForName"
"       \t- invalid peer certificate contents: invalid peer certificate: CertNotValidForName"
"       \t- invalid peer certificate contents: invalid peer certificate: CertNotValidForName"
"       \t- invalid peer certificate contents: invalid peer certificate: CertNotValidForName"
"       \t- invalid peer certificate contents: invalid peer certificate: CertNotValidForName"
"       "

## Your Environment

- Node version : 22.9.0
- Operating System and version : macOS latest version

**Comment by binarybaron** [comment]
Please upgrade to [0.6.4](https://github.com/UnstoppableSwap/unstoppableswap-gui/releases/tag/v0.6.4).

Thank you for the bug report.

**Comment by razlebol** [comment]
That fixed it. Thank you very much!
