### ISSUE TITLE
Swap did not work, now can't resume nor refund unfinished swap

### ISSUE THREAD

**Issue by ander-source** [UnstoppableSwap/unstoppableswap-gui#226]
## Explain what you did

I wanted to do a swap, but it did not work. Now I can't resume the swap nor manually refund it. 

## Which state is your swap in?

Unfinished swap, BTC is locked

## What is the problem?

can't refund or resume

## Your Environment

- Operating System: MacOS
- GUI Version: 0.6.4

**Comment by binarybaron** [comment]
Why can you not resume?

**Comment by ander-source** [comment]
when I try to resume, I receive the following error message: Error invoking remote method 'spawn-resume-swap'_ Error: connect ETIMEDOUT 0.0.0.0.:1234

**Comment by binarybaron** [comment]
Can you try restarting the GUI, and then resuming?

Also go to the _Help_ page and check if there is an error in the logging output.

**Comment by ander-source** [comment]
thank you, that worked
