### ISSUE TITLE
Trying to swap BTC for XMR and it has been stuck on "syncing monero wallet with blockchain, this may take a while" for hours...

### ISSUE THREAD

**Issue by Poweruser24** [UnstoppableSwap/unstoppableswap-gui#227]
Trying to exchange BTC for XMR. Sent roughly $540usd worth of BTC from Cashapp to the address provided in the GUI. This is my first experience with this app. I tried to use my new CakeWallet to have my XMR sent to, this would have been the first time i have used that as well. Im in Washington State. 

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	64.0 GB (63.7 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Home
Version	23H2
Installed on	‎6/‎11/‎2023
OS build	22631.4391
Experience	Windows Feature Experience Pack 1000.22700.1047.0

[log files.txt](https://github.com/user-attachments/files/17613924/log.files.txt)

**Comment by binarybaron** [comment]
This could be because the remote node the GUI chooses at startup, has gone offline.

Please try restarting the GUI and resuming the swap. It'll choose another availiable node.

**Comment by Alexahalid** [comment]
@Poweruser24 t seems like you're having some trouble with the BTC to XMR exchange process. It's essential to ensure that you're sending funds to the correct address and using trusted wallets like CakeWallet.I'll have to refer you to the official support live chat with the ticket ID GUI07638
Please see the link below to our dedicated support line:
[GUI wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Poweruser24** [comment]
forced shutdown, restarted gui and transfer finished without issue. thanks guys!

**Comment by binarybaron** [comment]
> forced shutdown, restarted gui and transfer finished without issue. thanks guys!

Awesome too hear! I'm gonna close this now
