### ISSUE TITLE
Adequate BTC sent to address, adequate confirmations, stuck at "Locking your BTC"

### ISSUE THREAD

**Issue by ExMrRig** [UnstoppableSwap/unstoppableswap-gui#228]
## Explain what you did

I followed the normal procedure and started a new swap, deposited BTC that exceeded the minimum to the specified address, and waited for the transaction to be confirmed. 

## Which state is your swap in?

It has not passed "Locking your BTC", despite the transaction being confirmed for multiple hours.

## What is the problem?

The transaction has not appeared to recognise my deposit.

## Logs

{"timestamp":"2024-11-04T02:56:33.2455522Z","level":"DEBUG","fields":{"message":"Network layer initialized","peer_id":"12D3KooWEr8jQVsBA6cb9HJu9moz6njP9vJFtezGiDMtEEpGpVMz"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:33.2455879Z","level":"DEBUG","fields":{"message":"Acquiring swap lock","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:33.2456999Z","level":"DEBUG","fields":{"message":"Requesting quote"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:39.0804433Z","level":"INFO","fields":{"message":"Connected to Alice","peer_id":"/dnsaddr/private-swap.click/p2p/12D3KooWA84aJevDy4ktdSn5zdpNyb9PBJGPrDh8aEQaxkyFdLJx"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:39.3869193Z","level":"INFO","fields":{"message":"Received quote","price":"0.00234646 BTC","minimum_amount":"0.001 BTC","maximum_amount":"0.61794446 BTC"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:44.8472946Z","level":"DEBUG","fields":{"message":"Estimated fee for transaction","weight":"485","fee_rate":"1.952","sats_per_vbyte":"236.68000"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:44.8473316Z","level":"WARN","fields":{"message":"Estimated fee of 236.68000 is smaller than the min relay fee, defaulting to min relay fee 1000"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:44.8473512Z","level":"INFO","fields":{"message":"Deposit at least 0.00101 BTC to cover the min quantity with fee!"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T02:56:44.8473871Z","level":"INFO","fields":{"message":"Waiting for Bitcoin deposit","deposit_address":"bc1qw9ayas0ju9fn7ytm6jv48qcmlm0grlpwx3207d","min_deposit_until_swap_will_start":"0.00101 BTC","max_deposit_until_maximum_amount_is_reached":"0.61795446 BTC","max_giveable":"0 BTC","minimum_amount":"0.001 BTC","maximum_amount":"0.61794446 BTC","min_bitcoin_lock_tx_fee":"0.00001 BTC","price":"0.00234646 BTC"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T04:35:29.6982398Z","level":"WARN","fields":{"message":"Lost connection to Alice","peer_id":"/dnsaddr/private-swap.click/p2p/12D3KooWA84aJevDy4ktdSn5zdpNyb9PBJGPrDh8aEQaxkyFdLJx","cause":"Connection error: Handler error: Ping timeout"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T04:35:31.7104528Z","level":"DEBUG","fields":{"message":"Dialling Alice","peer_id":"12D3KooWA84aJevDy4ktdSn5zdpNyb9PBJGPrDh8aEQaxkyFdLJx"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}
{"timestamp":"2024-11-04T04:35:38.5953076Z","level":"INFO","fields":{"message":"Connected to Alice","peer_id":"/dnsaddr/private-swap.click/p2p/12D3KooWA84aJevDy4ktdSn5zdpNyb9PBJGPrDh8aEQaxkyFdLJx"},"span":{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"},"spans":[{"log_reference_id":"\"10bbbe2c-5191-4db0-80db-d3623ec00ffa\"","method_name":"BuyXmr","swap_id":"b4146dbc-48fd-4e04-ad2f-d2eef2987b55","name":"method"}]}

## Your Environment

- Operating System: Windows 10
- GUI Version: 6.4

Apologies for editing this post, I had accidentally pressed submit before finishing. If you would like the transaction ID, please let me know.

**Comment by binarybaron** [comment]
The lock transaction hasn't been broadcast to the Bitcoin network yet, so your BTC is still safely held in your internal wallet. You can safely stop this swap and start a new one without any risk of losing funds.

Please let me know if you encounter this issue again. I do not know what caused this.

**Comment by ExMrRig** [comment]
Got a little nervous for a second, but the funds appeared in the wallet and opening another swap worked perfectly. Thank you.
