### ISSUE TITLE
Farcaster support: data needed for gui

### ISSUE THREAD

**Issue by zkao** [UnstoppableSwap/unstoppableswap-gui#31]
Farcaster node started pushing data to be sent to the farcaster "statefull-clients", such as this. Till now, all the data was in the logs, but we're creating some infrastructure to support more advanced clients (that in the future should connect using zmq to receive updates). 

Your feedback would be important, as you've probably the expert that already figured out most of the needed bits of information needed for the clients. If you could help us list those requirements, that would be awesome, and would also facilitate later integration into this gui

**Comment by binarybaron** [comment]
Thanks for reaching out! I must admit that I am not very familiar with your architecture yet, but I will try to read the RFCs as soon as I have some time. The basic things needed to make forecaster compatible with this GUI are:

- Ability to **retrieve information about swaps that have occurred/been started in the past**. Either by having a database that is easily accessible through software stacks other than Rust (Comit uses a sqlite database), or by having some sort of API/RPC that we can call to get this information. We need to be able to derive some basic information about the swap from this data (exchange rate, amounts, fees, etc.). We also need to know what state the swap is in and what actions the user can take (resume, cancel, refund, ...).
- Ability to **start/resume/cancel a swap** either by starting the binary in non-interactive mode or by calling an API/RPC.
- Ability to **receive status updates for a running swap**. Either by having the binary pipe logs to stdout/stderr in a format we can work with ( e.g. JSON) or by registering somewhere to send updates to the GUI (e.g. zeromq).
- Ability to **interact with internal wallet**. If Farcaster has an internal wallet that the user should have access to, we need a way to query the current balance and withdraw money from that wallet.

**Comment by binarybaron** [comment]
Closing this for now as farcaster has been abandonded.
