### ISSUE TITLE
Maintain list of electrum servers and monero nodes to use for cli

### ISSUE THREAD

**Issue by binarybaron** [UnstoppableSwap/unstoppableswap-gui#70]

**Comment by xmrswapme** [comment]
Hi! You can add our ElectrumX server to the list:

xmrswap.me:50002

Not sure if we want to open up our Monero daemon, but we run that too. I'll consider it.

**Comment by binarybaron** [comment]
This has been implemented for Monero nodes with https://github.com/UnstoppableSwap/unstoppableswap-gui/commit/9e17962a4c8c5f6b4aec9e2ee0d3edb71beafb24
