### ISSUE TITLE
Display QRCode for deposit address

### ISSUE THREAD

**Issue by binarybaron** [UnstoppableSwap/unstoppableswap-gui#89]

**Comment by xmrswapme** [comment]
Didn't know how else to contact you.. Do you have a logo for Unstoppable swap? I'd like to put it on our website https://xmrswap.me with a link to this GUI. This is a much better implementation than our Python Web version and should be the standard going forward. Ours, swapfe, needs a lot of work and I just don't have the time nor do I think there will be much interest once this GUI goes live on mainnet. I'll probably end up linking to this project on our GitHub anyhow. Thanks!

**Comment by binarybaron** [comment]
Sure, you can down the icon [here](https://github.com/UnstoppableSwap/unstoppableswap-gui/blob/main/assets/icon.png). It might change in the future though, more of a placeholder right now.
