### ISSUE TITLE
"Not a valid Monero address" when pasting in from Monero desktop GUI client

### ISSUE THREAD

**Issue by harmolipi** [UnstoppableSwap/unstoppableswap-gui#94]
## Summary

I simply opened up my Monero GUI desktop client, copied out the address, pasted it into UnstoppableSwap, and got the error "Not a valid Monero address". Is this an issue with UnstoppableSwap, are there different types of Monero addresses, or am I doing something else wrong?

**Comment by binarybaron** [comment]
The GUI currently defaults to testnet. Did you use a normal mainnet monero address or a stagenet address?

**Comment by harmolipi** [comment]
Oh man, yup, it looks like that was my mistake, sorry about that.

In that case, where can I find mainnet swap providers? If I go to unstoppableswap.net it looks like I can browse a few, but I don't see their peer IDs.

**Comment by binarybaron** [comment]
I've added a copy button for the multi address to UnstoppableSwap.net. Keep in mind that the CLI is still a bit complicated to use.

**Comment by harmolipi** [comment]
Awesome thanks, that looks great. So how does it work, if I paste the multi address from UnstoppableSwap.net into the desktop GUI, I can use it to send on the mainnet? I gave it a shot but it didn't show up, but maybe it takes some time or something.

**Comment by binarybaron** [comment]
Unfortunately, you can't use the GUI on mainnet at all atm. But you can use the CLI (https://github.com/comit-network/xmr-btc-swap/blob/master/docs/cli/README.md) to initiate a swap by supplying the copied multi address via the `--seller` argument.

**Comment by binarybaron** [comment]
If you want to try this, make sure to use the latest preview release.

**Comment by harmolipi** [comment]
Ahh good to know, thank you! We can close this out then, that makes sense. I'll give the CLI version a shot then, excited to try it out.
